=== nikitasatcik/Project_3/src/main/resources/first.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="root" type="rootType"/>

    <xs:complexType name="rootType">
        <xs:sequence>
            <xs:element name="person" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="firstName" type="xs:string"/>
                        <xs:element name="secondName" type="xs:string"/>
                        <xs:element name="placeOfBirth" type="TypeOfBirth"/>

                    </xs:sequence>
                    <xs:attribute name="modelName" type="xs:ID" use="required"/>
                </xs:complexType>

            </xs:element>
        </xs:sequence>

    </xs:complexType>
    <xs:complexType name="TypeOfBirth">
        <xs:sequence>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="country" type="TypeOfCountry"/>

        </xs:sequence>

    </xs:complexType>
    <xs:simpleType name="TypeOfCountry">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Ukraine"/>
            <xs:enumeration value="USA"/>

        </xs:restriction>

    </xs:simpleType>
</xs:schema>

=== nikitasatcik/Project_3/src/main/resources/first.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="first.xsd">
    <person modelName="a001">
        <firstName>Vasya</firstName>
        <secondName>Ivanov</secondName>
        <placeOfBirth>
            <city>Kiev</city>
            <country>Ukraine</country>
        </placeOfBirth>
    </person>

    <person modelName="a002">
        <firstName>Petya</firstName>
        <secondName>Sidorov</secondName>
        <placeOfBirth>
            <city>Gmerenka</city>
            <country>Ukraine</country>
        </placeOfBirth>
    </person>

</root>
